# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default_pic.jpg', upload_to='profile_picture')),
                ('isAdmin', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('META', 'META'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CHEM', 'CHEM')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
