# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MECH', 'MECH'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('META', 'META')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default_pic.jpg', upload_to='profile_pictures'),
        ),
    ]
